
FROM python:2.7

RUN mkdir /srv/queue-service
COPY requirements.txt /srv/queue-service/
RUN pip install -r /srv/queue-service/requirements.txt

COPY *.py /srv/queue-service/
COPY config.docker.ini /srv/queue-service/config.ini

WORKDIR /srv/queue-service

CMD python checker.py
