---
version: "3"
services:
  db:
    build:
      context: ./sql
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=blocked
      - POSTGRES_PASSWORD=blocked
  amqp:
    image: rabbitmq:3
    environment:
      - RABBITMQ_DEFAULT_USER=blocked
      - RABBITMQ_DEFAULT_PASS=blocked
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: -S 0.0.0.0:8080
    ports:
      - 8080:8080
    links:
      - db
      - amqp
  init:
    build:
      context: .
      dockerfile: Dockerfile
    command: php ../backend/create_queues.php
    links:
      - db
      - amqp
  record:
    build:
      context: .
      dockerfile: Dockerfile
    command: php ../backend/record_results.php
    depends_on:
      - init
    links:
      - db
      - amqp
  example:
    build:
      context: example-client
      dockerfile: Dockerfile
    command: -S 0.0.0.0:8081
    ports:
      - 8081:8081
    links:
      - api
  fakeprobe:
    build:
      context: backend/fakeprobe
      dockerfile: Dockerfile
    links:
      - amqp
  checker:
    build:
      context: backend/queue-services
      dockerfile: Dockerfile
    command: python checker.py
    links:
      - db
      - amqp
  metadata:
    build:
      context: backend/queue-services
      dockerfile: Dockerfile
    command: python metadata-gather.py
    links:
      - db
      - amqp







