global:
  - rules: &susp-rules
      zgm0: re:body:This domain has been suspended on (request|advice) from the
    blocktypes: &susp-types
      zgb0: SUSPENSION
isps:
- isp: T-Mobile
  match:
    m0: "re:url:^http://www\\.t-mobile\\.co\\.uk/service/wnw-mig/entry/"
    m1: "re:url:http://tmobile\\.ee\\.co\\.uk/common/system_error_pages/outage_wnw\\.html"
    m2: "re:url:^http://ee-outage\\.s3\\.amazonaws.com/outage-v1/outage-v1\\.html"
    m3: "re:url:^http://ee-outage\\.s3\\.amazonaws\\.com/content-blocked/content-blocked-v1\\.html"

- isp: EE
  match:
    m0: "re:url:^http://www\\.t-mobile\\.co\\.uk/service/wnw-mig/entry/"
    m1: "re:url:http://tmobile\\.ee\\.co\\.uk/common/system_error_pages/outage_wnw\\.html"
    m2: "re:url:^http://ee-outage\\.s3\\.amazonaws.com/outage-v1/outage-v1\\.html"
    m3: "re:url:^http://ee-outage\\.s3\\.amazonaws\\.com/content-blocked/content-blocked-v1\\.html"
    m4: "re:url:^http://ee-outage\\.s3\\.amazonaws\\.com/content-blocked/content-blocked-nobranding\\.html"
    m5: "re:url:^http://myaccount\\.ee\\.co\\.uk/anonymous-content-lock"
    m6: "re:url:^https://myaccount\\.ee\\.co\\.uk/anonymous-content-lock"
    m7: "re:url:^https://id\\.ee\\.co\\.uk/id/login"
    m8: "re:url:^http://radio-myaccount\\.ee\\.co\\.uk/app/radio"
    m9: "re:url:^https://myaccount\\.ee\\.co\\.uk/app/anonymous-content-lock"

- isp: Vodafone
  match:
    m1: "re:url:^http://online\\.vodafone\\.co\\.uk/dispatch/Portal/ContentControlServlet\\?type=restricted"
    m2: "re:url:^http://online\\.vodafone\\.co\\.uk/en_GB/assets/static/contentcontrol/branded/restricted_access\\.html"
    m3: "re:url:^http://online\\.vodafone\\.co\\.uk/en_GB/assets/static/contentcontrol/unbranded/restricted_access\\.html"
    m4: "re:url:^https?://www\\.vodafone\\.co\\.uk/restricted-content/branded-agerestricted\\.html?"
    m5: "re:url:^https?://www\\.vodafone\\.co\\.uk/restricted-content/branded-paym-agerestricted\\.html"

- &bt
  isp: BT
  blocktype:
    b0: "PARENTAL"
    b1: "COPYRIGHT"
    b2: "COPYRIGHT"
    b3: "COPYRIGHT"
    b4: "COPYRIGHT"
    b5: "MALWARE"
    <<: *susp-types
  category:
    c0: querystring:list
  match:
    m0: "re:url:^http://blockpage\\.bt\\.com/pcstaticpage/blocked\\.html"
    m1: "re:url:^http://www\\.ukispcourtorders\\.co\\.uk/"
    m2: "re:body:^<p> Error \\- site blocked </p>"
    m3: "re:body:^<p>Access to the websites listed on this page has been blocked pursuant to orders of the high court."
    m4: "re:body:^<p> Error .*? site blocked</p>"
    m5: "re:body:title>BT Protect Intercept Page<"
    <<: *susp-rules

- isp: BT-Unfiltered
  <<: *bt

- isp: BT-Strict
  <<: *bt

- &talktalk
  isp: TalkTalk
  blocktype:
    b0: "PARENTAL"
    b1: "PARENTAL"
    b2: "COPYRIGHT"
    b3: "COPYRIGHT"
    <<: *susp-types
  category:
    c0: querystring:urlclassname:base64
  match:
    m0: "re:body:http://www\\.talktalk\\.co\\.uk/notices/parental-controls.html\\?originalURL="
    m1: "re:url:^http://www\\.talktalk\\.co\\.uk/notice/parental-controls\\?accessurl"
    m2: "re:url:^http://www\\.siteblocked\\.org/.*\\.html\\?"
    m3: "re:body:<h1>Access to this website has been blocked under an Order of the Higher Court.</h1>"
    <<: *susp-rules

- isp: TalkTalk-unfiltered
  <<: *talktalk

- &plusnet
  isp: Plusnet
  blocktype:
    b0: "COPYRIGHT"
    b1: "COPYRIGHT"
    b2: "PARENTAL"
    b3: "COPYRIGHT"
    b4: "PARENTAL"
    b5: "PARENTAL"
    <<: *susp-types
  category:
    c0: querystring:category
  match:
    m0: "re:url:^http://www\\.ukispcourtorders\\.co\\.uk/"
    m1: "re:body:More information can be found at www\\.ukispcourtorders\\.co\\.uk"
    m2: "re:url:^http://www\\.plus\\.net/support/security/abuse/blocked\\.shtml"
    m3: "re:body:^<p> Error .*? site blocked</p>"
    m4: "re:url:^https://blocked\\.plus\\.net\\?originalURL"
    m5: "re:url:^https://blocked.plus.net/index/"
    <<: *susp-rules

- isp: Plusnet-unfiltered
  <<: *plusnet

- isp: Three
  match:
    m0: "re:url:^http://mobile\\.three\\.co\\.uk/pc/Live/pcreator/live/100004/pin/blocked"
    m1: "re:url:^http://mobile\\.three\\.co\\.uk/misc/pin/blocked"

- isp: AAISP
  match: {}

- isp: VirginMobile
  match:
    m0: "re:url:http://m\\.virginmedia\\.com/MiscPages/AdultWarning\\.aspx"

- isp: O2
  blocktype:
    b0: "PARENTAL"
    b1: "COPYRIGHT"
  match:
    m0: "re:url:http://assets\\.o2\\.co\\.uk/18plusaccess/"
    m1: "re:body:<span class=\"style12\" style=\"color:#1B224E;\"><br /><br />We're complying with a court order that means access to this website has<br />to be blocked to protect against copyright infringement\\."

- &sky
  isp: Sky
  blocktype:
    b0: "COPYRIGHT"
    b1: "PARENTAL"
    b2: "COPYRIGHT"
    b3: "PARENTAL"
    b4: "PARENTAL"
    <<: *susp-types
  category:
    c0: querystring:categories
  match:
    m0: "re:body:We are required by Court order to prevent access to this site"
    m1: "re:url:http://block\\.nb\\.sky\\.com/\\?"
    m2: "re:url:http://blocked\\.nb\\.sky\\.com/\\?"
    m3: "re:url:http://block\\.cf\\.sky\\.com/\\?"
    m4: "re:url:http://block\\.isp\\.sky\\.com/\\?"
    <<: *susp-rules

- isp: Sky-unfiltered
  <<: *sky

- &virginmedia
  isp: VirginMedia
  blocktype:
    b0: "COPYRIGHT"
    b1: "PARENTAL"
    b2: "PARENTAL"
    b3: "MALWARE"
    <<: *susp-types
  match:
    m0: "re:url:https?://assets\\.virginmedia\\.com/site-blocked\\.html"
    m1: "re:url:https?://assets\\.virginmedia\\.com/parental\\.html"
    m2: "re:url:https?://websafe\\.virginmedia\\.com/childsafe-blocked.html"
    m3: "re:url:https?://websafe\\.virginmedia\\.com/virussafe-blocked.html"
    <<: *susp-rules

- isp: VirginMedia-unfiltered
  <<: *virginmedia

- isp: Uno
  match: {}

- isp: PROXAD
  match: {}

- blocktype:
    b0: "COPYRIGHT"
  isp: Telekom-AT
  match:
    m0: "re:body:Aufgrund eines Sperrbegehrens nach &sect; 81 Abs 1 UrhG wurde diese Website gesperrt."

- isp: UPC-AT
  blocktype:
    b0: "COPYRIGHT"
  match:
    m0: "re:url:^https://www\\.upc\\.at/snippets/kundeninfo/"

- isp: XS4ALL
  blocktype:
    b0: "COPYRIGHT"
  match:
    m0: "re:url:^https://www.xs4all.nl/geblokkeerd/"

- isp: UPC-NL
  blocktype:
    b0: "COPYRIGHT"
  match:
    m0: "re:url:^https://www\\.ziggo\\.nl/yarrr/"

- isp: Belgacom
  blocktype:
    b0: "COPYRIGHT"
  match:
    m0: "re:body:stop page because the website you are trying to visit offers content"

- isp: GET NO
  blocktype:
    b0: "COPYRIGHT"
  match:
    m0: "re:url:^http://blokkert\\.get\\.no"

- isp: NextGenTel NO
  blocktype:
    b0: "COPYRIGHT"
  match:
    m0: "re:body:Oslo Tingrett har besluttet at NextGenTel skal hindre tilgang til det nettstedet du"

- isp: OpenDNS
  blocktype:
    b0: "MALWARE"
    b1: "PARENTAL"
  match:
    m0: "re:body:https://phish.opendns.com/\\?url="
    m1: "re:body:https://block.opendns.com/\\?url="

- isp: NOS
  blocktype:
    b0: "COPYRIGHT"
  match:
    m0: "re:body:title>Bloqueado por ordem judicial</title"

- isp: Vodafone PT
  blocktype:
    b0: "COPYRIGHT"
  match:
    m0: "re:url:http://mobilegen.vodafone.pt/denied/dn"

info:
  self-test:
    must-allow:
    - http://www.bbc.co.uk
    - http://www.google.co.uk
    must-block:
    - http://www.pornhub.com
    - http://www.youporn.com
  version: '2021031401'
  org-block-rules: 0.2.3
